# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-11-14 15:41:07
"""
import arcpy

def Anno_FIM():  # Anno_FIM

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = True

    Eingabekarte = "G:\\Projekte\\Test_GIS_Projekte\\Friedhofskataster\\FIM_WebOffice\\Friedhofskataster.mapx"
    FIM_2022_gdb_2_ = "G:\\Projekte\\Friedhofskataster\\FIM_2022\\FIM_2022.gdb"
    Beschriftung_Urnengraeber_anonym_2_ = "G:\\Projekte\\Test_GIS_Projekte\\Friedhofskataster\\FIM_WebOffice\\Beschriftung Urnengraeber.lyrx"
    directory2 = "G:\\Projekte\\Friedhofskataster\\FIM_2022\\FIM_2022.gdb"
    
    # Process: Beschriftungen in Annotation konvertieren (Beschriftungen in Annotation konvertieren) (cartography)
    Beschriftung_Urnengraeber_anonym = directory2 + "Beschriftung Urnengraeber_anonym"
    FIM_2022_gdb = arcpy.cartography.ConvertLabelsToAnnotation(input_map=Eingabekarte,
                                                               conversion_scale=100,
                                                               output_geodatabase=FIM_2022_gdb_2_,
                                                               anno_suffix="Annotation", extent="DEFAULT",
                                                               generate_unplaced="ONLY_PLACED",
                                                               require_symbol_id="NO_REQUIRE_ID",
                                                               feature_linked="STANDARD",
                                                               auto_create="AUTO_CREATE",
                                                               update_on_shape_change="SHAPE_UPDATE",
                                                               output_group_layer=Beschriftung_Urnengraeber_anonym,
                                                               which_layers="SINGLE_LAYER",
                                                               single_layer=Beschriftung_Urnengraeber_anonym_2_,
                                                               multiple_feature_classes="FEATURE_CLASS_PER_FEATURE_LAYER",
                                                               merge_label_classes="NO_MERGE_LABEL_CLASS")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"G:\Projekte\Test_GIS_Projekte\Friedhofskataster\FIM_WebOffice\FIM_WebOffice.gdb",
                          workspace=r"G:\Projekte\Test_GIS_Projekte\Friedhofskataster\FIM_WebOffice\FIM_WebOffice.gdb"):
        Anno_FIM()

try:
    input("Press enter to continue")
except SyntaxError:
    input("SythaxError")
